name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # AGP 8.2 requires 34.0.0-rc3 - see https://issuetracker.google.com/issues/236167971#comment36
    # and https://github.com/actions/runner-images/issues/7506#issuecomment-1533097084
    # TODO: Remove when AGP updates Build Tools to 34.0.0 and pre-installed in the runner
    - name: Install Android Build Tools 34.0.0-rc3
      run: echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "build-tools;34.0.0-rc3"
    - name: Build with Gradle
      run: ./gradlew build
